#!/bin/bash

# File for transfer to and from cluster local disk

# change in and out folder only

# folder is deleted on cluster after end

#######PBS -l nodes=1:ppn=4:NODE59
#PBS -l nodes=1:ppn=12
##### PBS -l nodes=6:ppn=16
#PBS -l walltime=20:00:00
#PBS -V
#PBS -l vmem=30gb
########PBS -l software=abaqus:12
#PBS -k eo

hkl=(1 1 0)
uvw=(0 0 1)

mode=I

suffix=${hkl[0]}${hkl[1]}${hkl[2]}_${uvw[0]}${uvw[1]}${uvw[2]}

inp_folder=inp_files_${suffix}
in_folder=/u/tezeghdanti/3D_Model_Crystal_Plasticity/Reference_Fields_For_Slip_Planes/${inp_folder}/Elastic

cat $PBS_NODEFILE > ${in_folder}/node_EL_${mode}_${PBS_JOBID}

out_folder_gnode=/data6/tezeghdanti/3D_Model_Crystal_Plasticity/Reference_Fields_For_Slip_Planes/${inp_folder}/Elastic

#today_dir=$(date +%F)
temp_folder=/usrtmp/tezeghdanti/${inp_folder}

echo $(hostname)

mkdir -p ${temp_folder}

cp -r $in_folder  $temp_folder/

cd $temp_folder/Elastic

####source ~zebulon/Z8.7/do_config.sh

JobName=$(sed -n 1p EL_job_details_${mode}.txt)

NewJobName="${JobName}.inp"

source /u/gosselet/Z8.6/do_config.sh

Zmat cpus=8 memory=32gb ${NewJobName}

echo "#########################Resync to origin################"

mkdir -p $out_folder_gnode

rsync -rtv $temp_folder/Elastic/ $out_folder_gnode/

rm -r $temp_folder/Elastic

#scp -r $out_folder_gnode/${inp_folder} $ou_folder_local/
